service: ignite-certificate

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  hello:
    handler: src/functions/handler.handle
    events:
      - http:
          path: /
          method: get
    